name: Deploy Frontend to Vercel

on:
  push:
    paths:
      - '**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install dependencies and build the React app
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Step 3: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_AUTH_TOKEN }}
        run: |
          npx vercel --prod --token $VERCEL_TOKEN
